.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GO\-CARPET" "" "November 2019" "" ""
.
.SH "NAME"
\fBgo\-carpet\fR \- show test coverage for Go source files
.
.P
To view the test coverage in the terminal, just run \fBgo\-carpet\fR\.
.
.P
It works outside of the \fBGOPATH\fR directory\. And it works recursively for multiple packages\.
.
.P
With \fB\-256colors\fR option, shades of green indicate the level of coverage\.
.
.P
By default skip vendor directories (Godeps,vendor), otherwise use \fB\-include\-vendor\fR option\.
.
.SH "Usage"
.
.nf

usage: go\-carpet [options] [paths]
  \-256colors
        use more colors on 256\-color terminal (indicate the level of coverage)
  \-args string
        pass additional arguments for go test
  \-file string
        comma\-separated list of files to test (default: all)
  \-func string
        comma\-separated functions list (default: all functions)
  \-include\-vendor
        include vendor directories for show coverage (Godeps, vendor)
  \-summary
        only show summary for each file
  \-version
        get version
.
.fi
.
.P
For view coverage in less, use \fB\-R\fR option:
.
.IP "" 4
.
.nf

go\-carpet | less \-R
.
.fi
.
.IP "" 0
.
.SH "Install"
From source:
.
.IP "" 4
.
.nf

go get \-u github\.com/msoap/go\-carpet
sudo ln \-s $(go env GOPATH)/bin/go\-carpet /usr/local/bin/go\-carpet
.
.fi
.
.IP "" 0
.
.P
Download binaries from: releases \fIhttps://github\.com/msoap/go\-carpet/releases\fR (OS X/Linux/Windows)
.
.P
Install from homebrew (OS X):
.
.IP "" 4
.
.nf

brew tap msoap/tools
brew install go\-carpet
# update:
brew upgrade go\-carpet
.
.fi
.
.IP "" 0
.
.P
.
.SH "See also"
.
.IP "\(bu" 4
blog\.golang\.org \fIhttps://blog\.golang\.org/cover\fR \- the cover story
.
.IP "\(bu" 4
gocover\.io \fIhttps://gocover\.io\fR \- simple Go test coverage service
.
.IP "\(bu" 4
coveralls\.io \fIhttps://coveralls\.io\fR \- test coverage service
.
.IP "\(bu" 4
package cover \fIhttps://godoc\.org/golang\.org/x/tools/cover\fR \- golang\.org/x/tools/cover
.
.IP "\(bu" 4
gotests \fIhttps://github\.com/cweill/gotests\fR \- Go commandline tool that generates table driven tests
.
.IP "\(bu" 4
docker\-golang\-checks \fIhttps://github\.com/msoap/docker\-golang\-checks\fR \- Go\-code checks Docker image
.
.IP "" 0

